name: Build for macOS M1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [aarch64-apple-darwin]

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --target ${{ matrix.target }}
